variables:
  DOCKER_CLI_EXPERIMENTAL: enabled
  IMAGE: {{ IMAGE }}
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
  REGISTRY: $REGISTRY_URI/$CI_PROJECT_PATH

stages:
  - Static Code Analysis
  - Create Image
  - Functional Tests
  - Promote Image
  - Clean

image: docker:19.03.8

.registry_template: &registry_login
  before_script:
  - export TAG=bld_$CI_PIPELINE_IID_${CI_COMMIT_SHA:0:7}
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $REGISTRY
  services: [ "docker:dind" ]

analysis:
  stage: Static Code Analysis
  image: instantlinux/python-builder:latest
  script: cd images/$IMAGE && make analysis

create_image:
  <<: *registry_login
  stage: Create Image
  script: apk add make && cd images/$IMAGE && make create_image
  services: [ { name: "docker:dind", command: ["--experimental"] } ]

test:
  stage: Functional Tests
  script: apk add make && cd images/$IMAGE && make test_functional

promote_image:
  only: {refs: [master]}
  stage: Promote Image
  <<: *registry_login
  script: apk add curl jq make && cd images/$IMAGE && make promote_image

clean:
  stage: Clean
  script:
  - export TAG=bld_$CI_PIPELINE_IID_${CI_COMMIT_SHA:0:7}
  - docker rmi $REGISTRY/$IMAGE:$TAG
  when: always
  except:
    variables: [ $REGISTRY_URI == "registry.gitlab.com" ]
  services: [ "docker:dind" ]
